# Makefile for EMX/gcc 0.8f using OS/2 and dmake 3.8.
# Adapted from the supplied Makefile.
#
# Darrel Hankerson hankedr@mail.auburn.edu or hank@ducvax.auburn.edu
# 1 March 1993

# bm2font compiling hints:
# for Next set -DNO_LACK
# for rs6000 set -DHAS_UCHAR
# for sun set -DNOSTDDEF
# any intel machine set -DINTEL
# Compiling everything:

#CC=cc -O -DNO_LACK -Wall # NeXT

#CC=gcc -O2 -DNO_LACK -DHAS_UCHAR -Wall -Wtraditional # RS6000 gcc, touchy

#CC=gcc -O -DNOSTDDEF  -Wall # sparc gcc
 
#CC=/usr/local/bin/gcc -O2 -traditional -I/usr/local/lib/gcc-include -DBSD -DHAS_STDLIB # Convex

#CC=gcc -O -Dmemmove=my_memmove -DNO_LACK -Wall # Mips thanks to Tim Murphy
 
#CC=gcc -O2 -traditional -DINTEL -DBSD -DHAS_STDLIB # Linux

#CC=cc +O1 -DBSD=1  -DHAS_STDLIB # HP-UX

# EMX/gcc
CC = gcc -O2 -DINTEL -Dshort=int -Zomf -Zmt

O = .obj
E = .exe

bm2font$E: bm2font$O p2clib$O loc.p2clib$O
	$(CC) -o $@ $< -lm 

bm2font$O: bm2font.c p2c.h
	$(CC) -c bm2font.c

p2clib$O: p2clib.c p2c.h
	$(CC) -c p2clib.c

loc.p2clib$O: loc.p2clib.c p2c.h
	$(CC) -c loc.p2clib.c

clean:
	rm -f *$O bm2font$E *.tfm *pk *.dvi *.log
